services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"

  customer-service:
    build: ./customer-service
    ports:
      - "8056:8056"
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service

  ebank-service:
    build: ./ebank-service
    ports:
      - "8057:8057"
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service

  gateway-service:
    build: ./getway-servicce
    ports:
      - "8058:8058"
    environment:
      - CONFIG_SERVER=http://host.docker.internal:8888
      - EUREKA_SERVER=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service