-- The schema is owned by Flyway and validated by Hibernate at startup
-- (spring.jpa.hibernate.ddl-auto=validate). Column types mirror what the
-- Customer entity maps to on PostgreSQL; any drift fails the build.

create table customer (
    id    bigint generated by default as identity primary key,
    name  varchar(255),
    email varchar(255)
);
