-- V2: accounts can now move money (deposits, withdrawals, transfers). Day-one
-- read-only accounts did not need either of the two things this migration adds.
--
-- 1. Optimistic locking. A version column lets the application detect that two
--    operations changed the same account concurrently: the second commit fails
--    instead of silently overwriting the first and losing a deposit. The column
--    carries a default so the rows created under V1 get a valid starting value.
--
-- 2. A transaction ledger. Every movement is written as an immutable row: this
--    is at once the customer's statement and the audit trail a real bank is
--    required to keep. A transfer writes two rows (one per account) sharing a
--    transfer_id, so the two sides of one transfer can be matched.
--
-- Column types mirror the AccountTransaction entity; money is numeric(19,4)
-- like the account balance, never floating point.

alter table bank_account
    add column version bigint not null default 0;

create table account_transaction (
    id                      bigint generated by default as identity primary key,
    type                    varchar(255)             not null,
    amount                  numeric(19, 4)           not null,
    balance_after           numeric(19, 4)           not null,
    account_id              varchar(255)             not null references bank_account (id),
    counterparty_account_id varchar(255),
    transfer_id             varchar(255),
    created_at              timestamp with time zone not null
);

-- A statement is "this account's movements, newest first"; this index serves
-- that query without scanning the whole ledger.
create index idx_account_transaction_account on account_transaction (account_id, created_at);
