spring.application.name=agent-service
server.port=8060

#configuration de l'ia

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1
spring.ai.ollama.chat.options.temperature=0.7

eureka.client.enabled=false

#configuration de la connection
spring.ai.mcp.client.streamable-http.connections.ebank.url=http://localhost:8058
spring.ai.mcp.client.streamable-http.connections.ebank.endpoint=/EBANK-SERVICE/mcp